#!/usr/bin/env bash

## Autostart Programs

# kill already running process
_ps=(waybar mako mpd)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
# /usr/lib/xfce-polkit/xfce-polkit &

# Set wallpaper
swaybg --output '*' --mode fill --image ~/.config/hypr/wallpapers/wallpaper.png &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
waybar -c ~/.config/hypr/waybar/config -s ~/.config/hypr/waybar/style.css &


# Start mpd
exec mpd &
